name: DVWA DAST Scan

on:
  push:
    branches: [ "master" ]

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start DVWA in Docker
        run: |
          docker run -d -p 8080:80 vulnerables/web-dvwa
          sleep 20  # wait for DVWA to start

      - name: Run AccuKnox DAST Scan
        uses: accuknox/dast-scan-action@latest
        with:
          target_url: "http://localhost:8080"
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_label: "dvwa-scan"
          severity_threshold: "HIGH"
          dast_scan_type: "full-scan"

      - name: Upload DAST Report
        uses: actions/upload-artifact@latest
        with:
          name: dast-report
          path: report.json
